### ISSUE TITLE
First Time Instructions

### ISSUE THREAD

**Issue by rocketinventor** [FellowHead/flpjck#2]
Hi!

I really like your project; it is very helpful. Right now it is helping me to batch render ~500 .flp's that I have made over the years.

The first run instructions, however, could use some work - It is not clear at all right now _how_ to actually execute the first step of the instructions. The instructions only say to "Install FlpJck". There are no installers or pre-built binaries under the "Release" tab, and no mentions in the `readme` to any package managers/script installs.

While trying to figure this out, I noticed the `package.json`, and attempted an NPM install using `NPM Install FlpJck`, `NPM Install flpjck`, `NPM Install [git URL]`, etc. Noting the yarn.lock file, I tried to do these actions over Yarn, also. No avail.

**This is how I was got FlpJck up and running:**

1. Git Clone Repository
2. `NPM Install` (in repository folder)
3. `NPM start` (in repository folder)

That's it! (but probably not the most ideal way to do the "install")

**Comment by doodle-alt** [comment]
Glad to know someone stumbled upon this project :D

I recommend using "npx electron-builder", which creates an executable FlpJck installer.
As soon as project the project is finished, I'll also upload some proper installers. I wrote the `readme` file as a placeholder, I guess. From a finished-project-perspective.

However, I kind of paused development because some rendered Fruity Loops projects didn't sound the way they should. For example, if there is any [Komplete Kontrol](https://www.native-instruments.com/products/komplete/bundles/komplete-kontrol/) plugin used in a project, the first few notes played by that instrument will not be included in your mp3 (I blame Fruity Loops).
The `automate` branch was an attempt at a workaround, sending simulated keystrokes to FL and triggering MIDI on every single instrument before rendering. The problem here is that I can't get [robotjs](http://robotjs.io/) working.

**Comment by doodle-alt** [comment]
Finally, a (hopefully) [stable release](https://github.com/FellowHead/FlpJck/releases/tag/v1.0) of FlpJck is finished! I uploaded installers for Windows and MacOS, so I'm guessing this issue can be closed.

In case anybody wants to build their own version of FlpJck:
- Clone the repository
- Execute the [yarn](https://classic.yarnpkg.com/en/) command in the root directory

To compress your source code into an executable file, run `npx electron-builder`.
